# Generated by Django 4.0.4 on 2022-05-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozylibrary', '0003_book_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='/covers/default.jpg', upload_to='covers/'),
        ),
    ]
