# Generated by Django 4.0.4 on 2022-05-11 03:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cozylibrary", "0004_alter_book_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000),
        ),
    ]
