# Generated by Django 4.0.4 on 2022-05-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cozylibrary", "0006_alter_book_author_alter_book_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="download_url",
            field=models.CharField(default="", max_length=666),
        ),
    ]
