# Generated by Django 4.0.4 on 2022-05-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cozylibrary", "0007_book_download_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="download_url",
        ),
    ]
